FORMAT: 1A
HOST: https://jr2xb1legd.execute-api.us-east-1.amazonaws.com/dev/

# hamilton-webapi

A simple web API powered by Serverless (Node.js) and DynamoDB, intended as a starting point for Serverless web APIs. This project uses serverless-webpack with Babel to compile handler functions written in ES6.

# Group Orders
Operations to retrieve/update Orders.

## Orders [/orders]

### Get all Orders [GET]

+ Response 200 (application/json; charset=utf-8)

    + Attributes

        + orders (array[FullOrder])

### Get a single Order [GET /orders/{id}]

+ Parameters
    + id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)

+ Response 200 (application/json; charset=utf-8)

    + Attributes (FullOrder)

### Create an Order [POST]

+ Request (application/json; charset=utf-8)
    + Body

            {
                "name" : "James Bond"
            }

+ Response 200 (application/json; charset=utf-8)

    + Attributes (FullOrder)

### Edit an Order [PATCH /orders/{id}]

+ Parameters
    + id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)

+ Request (application/json; charset=utf-8)
    + Body

            {
                "name" : "Jim Bond"
            }

+ Response 200 (application/json; charset=utf-8)

    + Attributes (UpdatedOrder)

### Delete an Order [DELETE /orders/{id}]

+ Parameters
    + id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)

+ Response 200


## Data Structures

### FullOrder (object)
+ id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)
+ name: James Bond (string, required)
+ createdUtc: `2016-10-17T00:00:00.000Z` (string, required)

### UpdatedOrder (object)
+ id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)
+ name: Jim Bond (string, required)
