image: madmobile/hamilton:latest
pipelines:
  branches:
    master:
      - step:
          script:
            - yarn install
            - export NODE_ENV=production
            - serverless deploy
